
#Types of Armour
[armour_sets]
	#List of items that should play the metal clanking/hit sounds.
	#Format: 'modid:item_name'
	metal_armour = ["minecraft:iron_helmet", "minecraft:iron_chestplate", "minecraft:iron_leggings", "minecraft:iron_boots", "minecraft:golden_helmet", "minecraft:golden_chestplate", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:diamond_helmet", "minecraft:diamond_chestplate", "minecraft:diamond_leggings", "minecraft:diamond_boots", "minecraft:netherite_helmet", "minecraft:netherite_chestplate", "minecraft:netherite_leggings", "minecraft:netherite_boots"]
	#List of items that should play the chainmail rustling/hit sounds.
	mail_armour = ["minecraft:chainmail_helmet", "minecraft:chainmail_chestplate", "minecraft:chainmail_leggings", "minecraft:chainmail_boots"]
	#List of items that should play the leather hit sounds.
	leather_armour = ["minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots"]
	#Choose what method to determine the condition for playing armour sounds.
	#OFF: Default Method
	#ALL_METAL: Makes all armour play metal clanking/hit sounds
	#ALL_MAIL: Makes all armour play mail rustling/hit sounds
	#Allowed Values: OFF, ALL_METAL, ALL_MAIL
	all_armours_are = "OFF"

